################################################################################
### generated-with:
###   type: R-package
###   name: kwb.pkgbuild
###   version: 0.1.6
###   installed-from: local
###   installed-on: '2020-11-24'
### generated-by:
###   user: mrustl
###   function-call: kwb.pkgbuild::use_autopkgdown()
### generated-on: 2020-12-04 10:13:20
################################################################################


pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - gh-pages
