---
title: "Zulässiger Einleitabfluss"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

<style>                     
.navbar {
  background-color: #007c9f;
  border-color:black;
}
.navbar-brand {
color:white !important;
}
</style>   


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyr)
library(ggplot2)
library(plotly)
library(DT)

# Example plot:

grid <- tidyr::expand_grid(A_E0 = 1:200, A_ba = seq(.1, 10, .1))

grid$q_zul <- 1
grid$allowed_Aba <- 1
grid$allowed_fDA <- 1


for (i in 1:nrow(grid)){

  grid$q_zul[i] <- r2q::get_q_zulaessig(A_ba = grid$A_ba[i], A_E0 = grid$A_E0[i])
  grid$allowed_Aba[i] <- r2q::get_allowed_area(q_zul = grid$q_zul[i])
  grid$allowed_fDA[i] <- r2q::get_average_runoff_coef(A_ba = grid$A_ba[i], 
                                                 q_zul = grid$q_zul[i],
                                                 R_Spende = 150)

}

```
Overview
========================================

Column {data-width=300 .sidebar}
--------------------------------------------------------------------------

### Sliders

```{r}

shiny::sliderInput("river_slider",
            "River catchment [km²]",
            min = 1,
            max = 300,
            value = c(30,50),
            step = .1)

shiny::sliderInput("planning_slider",
                   "Planning area [km²]",
                   min = 0.1,
                   max = 10,
                   value = c(3,5),
                   step = .1)

#shiny::selectInput("grouping_choice",
 #                  "Gruppierung nach Spalte",
  #                 choices = c("status", "streamed", "downloaded"))

show_threshold_df <- shiny::reactive({ grid %>%
 filter(A_E0 <= input$river_slider[2]&
          A_E0 >= input$river_slider[1])%>%
 filter(A_ba < input$planning_slider[2]&
        A_ba > input$planning_slider[1]  ) 

})

#jobs_all <- shiny::reactive({jobs %>%
# filter(date>=Sys.Date()-input$time_slider[2]&
 #         date <=Sys.Date()-input$time_slider[1])})


```



Column {data-width=350}
-----------------------------------------------------------------------

### Tolerable discharge as a function of catchment and planning area

```{r}

plot <- grid %>% 
  ggplot(mapping= aes(x = A_ba, y = A_E0,  fill = q_zul))+ 
  geom_tile()+ 
  scale_color_viridis_c() + 
  scale_fill_viridis_c() + 
  ggtitle("Zulässige Einleitmenge")
  
plotly::ggplotly(plot)
  
```


### Annahme Gefälle


```{r}
flexdashboard::renderValueBox(
  flexdashboard::valueBox(prettyNum(0.1, big.mark = ','), 
                          color = "#007c9f",
                          caption = "Gefälle des Einzugsgebiets in %",
                          icon = "ion-navigate")
  )

```


### Annahme Faktor x


```{r}
flexdashboard::renderValueBox(
  flexdashboard::valueBox(prettyNum(0.1, big.mark = ','),
                          color = "#007c9f",
                          caption = "Annahme für Faktor x (Verhältnis Hq1,pnat, Hq2,pnat)",
                          icon = "ion-ios-partlysunny")
  )
#<i class="fas fa-cloud-rain"></i>
```

### Regensprende: 150l/s*ha

```{r}
renderValueBox(valueBox(prettyNum(150, big.mark = ','), color = "#007c9f",
                     caption = "Annahme für Regenspende rf", 
                     icon = "ion-ios-partlysunny"))
#<i class="fas fa-cloud-rain"></i>
```



### fd: 0.7

```{r}
renderValueBox(valueBox(prettyNum(0.7, big.mark = ','), color = "#007c9f",
                     caption = "Annahme für durchläsige befestigte Fläche", 
                     icon = "ion-ios-partlysunny"))
#<i class="fas fa-cloud-rain"></i>
```


Column{data-width=350}
------------------------------------------------


### Tolerierbare angeschlossene Fläche

```{r}

shiny::renderPlot(show_threshold_df() %>% 
ggplot(mapping= aes(x = A_ba, y = A_E0, col = q_zul, fill = q_zul))+ 
geom_tile() + 
scale_color_viridis_c() + 
scale_fill_viridis_c() +
xlab("befestigte Fläche [km²]") + 
ylab("Einzugsgebietsfläche bis Einleitstelle [km²]") +
ggtitle(bquote("Zulässige Einleitmenge" ~Q[E1][','][zul]))) 


plot <- grid %>% 
ggplot(mapping= aes(x = A_ba, y = A_E0,  fill = allowed_Aba)) + 
geom_tile()+ scale_color_viridis_c() + scale_fill_viridis_c() + 
ggtitle("Zulässige befestigte Fläche für fD = 0.7")
  
ggplotly(plot)

```

### Abminderungswerte in Abhängikeit der Fläche


```{r}

#renderPlot(show_threshold_df() %>% ggplot(mapping= aes(x = A_ba, y = A_E0, col = q_zul, fill = q_zul))+ 
 # geom_tile()+ scale_color_viridis_c() + scale_fill_viridis_c() +
#  xlab("befestigte Fläche [km²]") + 
#  ylab("Einzugsgebietsfläche bis Einleitstelle [km²]") +
#  ggtitle(bquote("Zulässige Einleitmenge" ~Q[E1][','][zul]))) 

plot <- grid %>% ggplot(mapping= aes(x = A_ba, y = A_E0,  fill = allowed_fDA))+ 
  geom_tile() + 
  ggtitle("Zulässiger durchschnittlicher Abminderungswert")
  
ggplotly(plot)


```


Data
====================================

Column

--------------------------------------


```{r}
DT::datatable(
  grid, 
  rownames = FALSE,
  extensions = 'Buttons', 
  options = list(dom = 'Bfrtip',
                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  )
)
```




