#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-07-14 11:50:23.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_functionsID() works", {

  f <- r2q:::get_functionsID

  result <- r2q:::get_functionsID()

  expect_s3_class(result, "data.frame")
  
  expect_identical(
    names(result), 
    c("f_id", "primary_function", "char1", "char2", "char3")
  )
})
