#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-18 11:21:34.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_average_runoff_coef() works", {

  f <- r2q:::get_average_runoff_coef

  expect_error(
    r2q:::get_average_runoff_coef()
    # Argument "q_zul" fehlt (ohne Standardwert)
  )

})
