#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-07-14 11:50:24.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("load_planning_details() works", {

  f <- r2q:::load_planning_details

  expect_error(
    r2q:::load_planning_details()
    # argument "data.dir" is missing, with no default
  )

})
