#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-07-14 11:50:24.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("Input_event() works", {

  f <- r2q:::Input_event

  expect_error(
    r2q:::Input_event()
    # argument "area_runoff" is missing, with no default
  )

})
