#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-03 11:55:01.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_allowed_area() works", {

  expect_error(
    r2q:::get_allowed_area()
    # argument "q_zul" is missing, with no default
  )

})

