#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-18 11:21:38.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_KOSTRA() works", {

  f <- r2q:::get_KOSTRA

  r2q:::get_KOSTRA()

})
