#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-03 11:55:02.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("load_site_data() works", {

  expect_error(
    r2q:::load_site_data()
    # argument "data.dir" is missing, with no default
  )

})

