#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-03 11:55:01.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("merge_by_pollutant() works", {

  expect_error(
    r2q:::merge_by_pollutant()
    # argument "dataFrame1" is missing, with no default
  )

})

