#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-03 11:55:02.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("mixed_reactor_C() works", {

  expect_error(
    r2q:::mixed_reactor_C()
    # argument "q_rain" is missing, with no default
  )

})

