#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-03 11:55:02.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("max_area_steady_state() works", {

  expect_error(
    r2q:::max_area_steady_state()
    # argument "Ci_river" is missing, with no default
  )

})

