#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-07-14 11:50:25.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("run_status_quo() works", {

  f <- r2q:::run_status_quo

  expect_error(
    r2q:::run_status_quo()
    # argument "filename" is missing, with no default
  )

})
