#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-07-14 11:50:22.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("hydrology_assessment() works", {

  f <- r2q:::hydrology_assessment

  expect_error(
    r2q:::hydrology_assessment()
    # argument "site_data" is missing, with no default
  )

})
