#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-07-14 11:50:23.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("sub_OgRe_to_name() works", {

  f <- r2q:::sub_OgRe_to_name

  expect_error(
    r2q:::sub_OgRe_to_name()
    # argument "c_table" is missing, with no default
  )

})
