#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-03 11:55:01.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_default_background() works", {

  result <- r2q:::get_default_background()

  expect_s3_class(result, "data.frame")
  expect_identical(names(result), c("s_id", "substance", "Unit", "Default"))
})
