#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-18 11:21:39.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("max_area() works", {

  f <- r2q:::max_area

  expect_error(
    r2q:::max_area()
    # Argument "C_river" fehlt (ohne Standardwert)
  )

})
