#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-07-14 11:50:22.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_HQ_time_interval() works", {

  f <- r2q:::get_HQ_time_interval

  expect_error(f())

})
