#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-03 11:55:01.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("import_hydrology_data() works", {

  expect_error(
    r2q:::import_hydrology_data()
    # '' does not exist in current working directory ('C:/Users/mzamzo/Documents/R/git/r2q').
  )

})

