#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-03 11:55:01.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_Hq1_pnat() works", {

  f <- r2q:::get_Hq1_pnat
  
  result <- f(slope = 0.1, area_catch = 1)

  expect_true(is.numeric(result))
  expect_length(result, 1L)
})
